      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     3 NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     4 CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,KSTEP,KINC)
C
      INCLUDE 'ABA_PARAM.INC'
C
      CHARACTER*80 CMNAME
      INTEGER K1, K2
      DOUBLE PRECISION STRESS(NTENS),STATEV(NSTATV),
     1 DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     2 STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     3 PROPS(NPROPS),COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3),
     4 B(3,3),DISTGR(3,3)
C------------------------------------------------------------------
C UMAT FOR COMPRESSIBLE HYPERELASTICITY BASED ON LODE INVARIANTS
C------------------------------------------------------------------
C-----------------------MATERIAL PROPERTIES------------------------
      DOUBLE PRECISION MU, KPA, DET, SCALE, ONE, THREE
      PARAMETER (ONE=1.0D0, THREE=3.0D0)
C
      MU  = PROPS(1)
      KPA = PROPS(2)
C------------------------------------------------------------------
C Compute determinant of deformation gradient and isochoric part
C------------------------------------------------------------------
      DET = DFGRD1(1,1)*(DFGRD1(2,2)*DFGRD1(3,3) - DFGRD1(2,3)*DFGRD1(3,2))
     1    - DFGRD1(1,2)*(DFGRD1(2,1)*DFGRD1(3,3) - DFGRD1(2,3)*DFGRD1(3,1))
     2    + DFGRD1(1,3)*(DFGRD1(2,1)*DFGRD1(3,2) - DFGRD1(2,2)*DFGRD1(3,1))
C
      SCALE = DET**(-ONE/THREE)
C
      DO K1 = 1, 3
         DO K2 = 1, 3
            DISTGR(K2,K1) = SCALE * DFGRD1(K2,K1)
         END DO
      END DO
C
C     CALL DGEMM('N','T',3,3,3,1.0D0,DFGRD1,3,DFGRD1,3,0.0D0,B,3)
C     Equivalent to: B = MATMUL(F, TRANSPOSE(F))
      B=MATMUL(DFGRD1,TRANSPOSE(DFGRD1))
C------------------------------------------------------------------

C------------------------------DDSDDE---------------------------------
C     --- User material for hyperelastic material
C     --- Automatically generated by Mathematica

C --- STRESS_BLOCK_START
      STRESS(1) = -0.3333333333333333*(6*DET*KPA - 6*DET**2*KPA -
     $ 4*MU*B(1,1) + 2*MU*B(2,2) + 2*MU*B(3,3))/DET
      STRESS(2) = 2*(-1 + DET)*KPA - (2*MU*(B(1,1) - 2*B(2,2) +
     $ B(3,3)))/(3.*DET)
      STRESS(3) = 2*(-1 + DET)*KPA - (2*MU*(B(1,1) + B(2,2) -
     $ 2*B(3,3)))/(3.*DET)
      STRESS(4) = (2*MU*B(1,2))/DET
      STRESS(5) = (2*MU*B(2,3))/DET
      STRESS(6) = (2*MU*B(1,3))/DET
C --- STRESS_BLOCK_END

C --- DDSDDE_BLOCK_START
      DDSDDE(1,1) = 2*(-1 + 2*DET)*KPA + (2*MU*((2*B(1,1))/3. +
     $ (2*(B(1,1) + B(2,2) + B(3,3)))/9.))/DET
      DDSDDE(1,2) = 2*(-1 + 2*DET)*KPA + (2*MU*((-2*B(1,1))/3. -
     $ (2*B(2,2))/3. + (2*(B(1,1) + B(2,2) + B(3,3)))/9.))/DET
      DDSDDE(1,3) = 2*(-1 + 2*DET)*KPA + (2*MU*((-2*B(1,1))/3. -
     $ (2*B(3,3))/3. + (2*(B(1,1) + B(2,2) + B(3,3)))/9.))/DET
      DDSDDE(1,4) = (2*MU*B(1,2))/(3.*DET)
      DDSDDE(1,5) = (-4*MU*B(2,3))/(3.*DET)
      DDSDDE(1,6) = (2*MU*B(1,3))/(3.*DET)
      DDSDDE(2,1) = DDSDDE(1,2)
      DDSDDE(2,2) = 2*(-1 + 2*DET)*KPA + (2*MU*((2*B(2,2))/3. +
     $ (2*(B(1,1) + B(2,2) + B(3,3)))/9.))/DET
      DDSDDE(2,3) = 2*(-1 + 2*DET)*KPA + (2*MU*((-2*B(2,2))/3. -
     $ (2*B(3,3))/3. + (2*(B(1,1) + B(2,2) + B(3,3)))/9.))/DET
      DDSDDE(2,4) = (2*MU*B(1,2))/(3.*DET)
      DDSDDE(2,5) = (2*MU*B(2,3))/(3.*DET)
      DDSDDE(2,6) = (-4*MU*B(1,3))/(3.*DET)
      DDSDDE(3,1) = DDSDDE(1,3)
      DDSDDE(3,2) = DDSDDE(2,3)
      DDSDDE(3,3) = 2*(-1 + 2*DET)*KPA + (2*MU*((2*B(3,3))/3. +
     $ (2*(B(1,1) + B(2,2) + B(3,3)))/9.))/DET
      DDSDDE(3,4) = (-4*MU*B(1,2))/(3.*DET)
      DDSDDE(3,5) = (2*MU*B(2,3))/(3.*DET)
      DDSDDE(3,6) = (2*MU*B(1,3))/(3.*DET)
      DDSDDE(4,1) = DDSDDE(1,4)
      DDSDDE(4,2) = DDSDDE(2,4)
      DDSDDE(4,3) = DDSDDE(3,4)
      DDSDDE(4,4) = (MU*(B(1,1) + B(2,2)))/DET
      DDSDDE(4,5) = (MU*B(1,3))/DET
      DDSDDE(4,6) = (MU*B(2,3))/DET
      DDSDDE(5,1) = DDSDDE(1,5)
      DDSDDE(5,2) = DDSDDE(2,5)
      DDSDDE(5,3) = DDSDDE(3,5)
      DDSDDE(5,4) = DDSDDE(4,5)
      DDSDDE(5,5) = (MU*(B(2,2) + B(3,3)))/DET
      DDSDDE(5,6) = (MU*B(1,2))/DET
      DDSDDE(6,1) = DDSDDE(1,6)
      DDSDDE(6,2) = DDSDDE(2,6)
      DDSDDE(6,3) = DDSDDE(3,6)
      DDSDDE(6,4) = DDSDDE(4,6)
      DDSDDE(6,5) = DDSDDE(5,6)
      DDSDDE(6,6) = (MU*(B(1,1) + B(3,3)))/DET
C --- DDSDDE_BLOCK_END


      RETURN
      END      